""" mpgui_ui.py --

 UI generated by GUI Builder Build 146 on 2011-12-18 02:16:27 from:
    /home/nimmer/code/mp-layer/gui-layout/mpgui.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Mpgui(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._frame_2 = Tkinter.Frame(root,
        )
        self._labelframe_3 = Tkinter.LabelFrame(root,
            text = "URL",
        )
        self._frame_4 = Tkinter.Frame(self._frame_2,
        )
        self._frame_5 = Tkinter.Frame(self._frame_2,
        )
        self._frSmart = Tkinter.Frame(self._frame_5,
        )
        self._labelframe_4 = Tkinter.LabelFrame(self._frame_5,
            text = "Name",
        )
        self._labelframe_5 = Tkinter.LabelFrame(self._frame_5,
            text = "Extension",
        )
        self._labelframe_1 = Tkinter.LabelFrame(self._frSmart,
            text = "Season",
        )
        self._labelframe_2 = Tkinter.LabelFrame(self._frSmart,
            text = "Episode",
        )
        self._txtSource = Tkinter.Text(self._labelframe_3,
            height = 4,
            width = 0,
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_1,
            height = 0,
            width = 0,
        )
        self._butDownload = Tkinter.Button(self._frame_1,
            text = "Download",
            width = 10,
        )
        self._butCancel = Tkinter.Button(self._frame_1,
            text = "Cancel",
            width = 10,
        )
        self._sclNames = Tkinter.Scrollbar(self._frame_4,
        )
        self._lstNames = Tkinter.Listbox(self._frame_4,
            height = 0,
            width = 0,
        )
        self._chkSmart = Tkinter.Checkbutton(self._frame_5,
            text = "Smart Naming",
        )
        self._panedwindow_2 = Tkinter.PanedWindow(self._frame_5,
            height = 0,
            width = 0,
        )
        self._spnSeason = Tkinter.Spinbox(self._labelframe_1,
            width = 10,
        )
        self._spnEpisode = Tkinter.Spinbox(self._labelframe_2,
            width = 10,
        )
        self._txtName = Tkinter.Text(self._labelframe_4,
            height = 0,
            width = 55,
        )
        self._lstExtension = Tkinter.Listbox(self._labelframe_5,
            height = 4,
            width = 0,
        )
        self._sclExtension = Tkinter.Scrollbar(self._labelframe_5,
        )

        # widget commands

        self._txtSource.configure(
            xscrollcommand = self._txtSource_xscrollcommand
        )
        self._txtSource.configure(
            yscrollcommand = self._txtSource_yscrollcommand
        )
        self._butDownload.configure(
            command = self._butDownload_command
        )
        self._butCancel.configure(
            command = self._butCancel_command
        )
        self._sclNames.configure(
            command = self._sclNames_command
        )
        self._lstNames.configure(
            xscrollcommand = self._lstNames_xscrollcommand
        )
        self._lstNames.configure(
            yscrollcommand = self._lstNames_yscrollcommand
        )
        self._chkSmart.configure(
            command = self._chkSmart_command
        )
        self._spnSeason.configure(
            command = self._spnSeason_command
        )
        self._spnSeason.configure(
            invalidcommand = self._spnSeason_invalidcommand
        )
        self._spnSeason.configure(
            validatecommand = self._spnSeason_validatecommand
        )
        self._spnSeason.configure(
            xscrollcommand = self._spnSeason_xscrollcommand
        )
        self._spnEpisode.configure(
            command = self._spnEpisode_command
        )
        self._spnEpisode.configure(
            invalidcommand = self._spnEpisode_invalidcommand
        )
        self._spnEpisode.configure(
            validatecommand = self._spnEpisode_validatecommand
        )
        self._spnEpisode.configure(
            xscrollcommand = self._spnEpisode_xscrollcommand
        )
        self._txtName.configure(
            xscrollcommand = self._txtName_xscrollcommand
        )
        self._txtName.configure(
            yscrollcommand = self._txtName_yscrollcommand
        )
        self._lstExtension.configure(
            xscrollcommand = self._lstExtension_xscrollcommand
        )
        self._lstExtension.configure(
            yscrollcommand = self._lstExtension_yscrollcommand
        )
        self._sclExtension.configure(
            command = self._sclExtension_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_3.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_4.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_5.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frSmart.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_4.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 5,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_5.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_1.grid(
            in_    = self._frSmart,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._labelframe_2.grid(
            in_    = self._frSmart,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txtSource.grid(
            in_    = self._labelframe_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._panedwindow_1.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butDownload.grid(
            in_    = self._frame_1,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butCancel.grid(
            in_    = self._frame_1,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._sclNames.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )
        self._lstNames.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._chkSmart.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 5,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._panedwindow_2.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._spnSeason.grid(
            in_    = self._labelframe_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._spnEpisode.grid(
            in_    = self._labelframe_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._txtName.grid(
            in_    = self._labelframe_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._lstExtension.grid(
            in_    = self._labelframe_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._sclExtension.grid(
            in_    = self._labelframe_5,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 48, pad = 0)
        root.grid_rowconfigure(2, weight = 1, minsize = 374, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 39, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 803, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(5, weight = 1, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frSmart.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frSmart.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frSmart.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
        self._labelframe_1.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_2.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_2.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_3.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_3.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_4.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_4.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._labelframe_5.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_5.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._labelframe_5.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


