#!/usr/bin/env python""" mpgui.py --

 UI generated by GUI Builder Build 146 on 2011-12-18 02:16:27 from:
    /home/nimmer/code/mp-layer/gui-layout/mpgui.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from mpgui_ui import Mpgui

# BEGIN USER CODE global

# END USER CODE global

class CustomMpgui(Mpgui):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _butCancel_command --
    #
    # Callback to handle _butCancel widget option -command
    def _butCancel_command(self, *args):
        pass

    # _butDownload_command --
    #
    # Callback to handle _butDownload widget option -command
    def _butDownload_command(self, *args):
        pass

    # _chkSmart_command --
    #
    # Callback to handle _chkSmart widget option -command
    def _chkSmart_command(self, *args):
        pass

    # _lstExtension_xscrollcommand --
    #
    # Callback to handle _lstExtension widget option -xscrollcommand
    def _lstExtension_xscrollcommand(self, *args):
        pass

    # _lstExtension_yscrollcommand --
    #
    # Callback to handle _lstExtension widget option -yscrollcommand
    def _lstExtension_yscrollcommand(self, *args):
        pass

    # _lstNames_xscrollcommand --
    #
    # Callback to handle _lstNames widget option -xscrollcommand
    def _lstNames_xscrollcommand(self, *args):
        pass

    # _lstNames_yscrollcommand --
    #
    # Callback to handle _lstNames widget option -yscrollcommand
    def _lstNames_yscrollcommand(self, *args):
        pass

    # _sclExtension_command --
    #
    # Callback to handle _sclExtension widget option -command
    def _sclExtension_command(self, *args):
        pass

    # _sclNames_command --
    #
    # Callback to handle _sclNames widget option -command
    def _sclNames_command(self, *args):
        pass

    # _spnEpisode_command --
    #
    # Callback to handle _spnEpisode widget option -command
    def _spnEpisode_command(self, *args):
        pass

    # _spnEpisode_invalidcommand --
    #
    # Callback to handle _spnEpisode widget option -invalidcommand
    def _spnEpisode_invalidcommand(self, *args):
        pass

    # _spnEpisode_validatecommand --
    #
    # Callback to handle _spnEpisode widget option -validatecommand
    def _spnEpisode_validatecommand(self, *args):
        pass

    # _spnEpisode_xscrollcommand --
    #
    # Callback to handle _spnEpisode widget option -xscrollcommand
    def _spnEpisode_xscrollcommand(self, *args):
        pass

    # _spnSeason_command --
    #
    # Callback to handle _spnSeason widget option -command
    def _spnSeason_command(self, *args):
        pass

    # _spnSeason_invalidcommand --
    #
    # Callback to handle _spnSeason widget option -invalidcommand
    def _spnSeason_invalidcommand(self, *args):
        pass

    # _spnSeason_validatecommand --
    #
    # Callback to handle _spnSeason widget option -validatecommand
    def _spnSeason_validatecommand(self, *args):
        pass

    # _spnSeason_xscrollcommand --
    #
    # Callback to handle _spnSeason widget option -xscrollcommand
    def _spnSeason_xscrollcommand(self, *args):
        pass

    # _txtName_xscrollcommand --
    #
    # Callback to handle _txtName widget option -xscrollcommand
    def _txtName_xscrollcommand(self, *args):
        pass

    # _txtName_yscrollcommand --
    #
    # Callback to handle _txtName widget option -yscrollcommand
    def _txtName_yscrollcommand(self, *args):
        pass

    # _txtSource_xscrollcommand --
    #
    # Callback to handle _txtSource widget option -xscrollcommand
    def _txtSource_xscrollcommand(self, *args):
        pass

    # _txtSource_yscrollcommand --
    #
    # Callback to handle _txtSource widget option -yscrollcommand
    def _txtSource_yscrollcommand(self, *args):
        pass

    # _ckSmart_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _ckSmart_command(self, *args):
        pass

    # _lsExtension_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _lsExtension_xscrollcommand(self, *args):
        pass

    # _lsExtension_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _lsExtension_yscrollcommand(self, *args):
        pass

    # _scExtension_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scExtension_command(self, *args):
        pass

    # _scNames_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scNames_command(self, *args):
        pass

    # _spEpisode_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spEpisode_command(self, *args):
        pass

    # _spEpisode_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spEpisode_invalidcommand(self, *args):
        pass

    # _spEpisode_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spEpisode_validatecommand(self, *args):
        pass

    # _spEpisode_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spEpisode_xscrollcommand(self, *args):
        pass

    # _spSeason_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spSeason_command(self, *args):
        pass

    # _spSeason_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spSeason_invalidcommand(self, *args):
        pass

    # _spSeason_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spSeason_validatecommand(self, *args):
        pass

    # _spSeason_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _spSeason_xscrollcommand(self, *args):
        pass

    # _txName_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _txName_xscrollcommand(self, *args):
        pass

    # _txName_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _txName_yscrollcommand(self, *args):
        pass

    # _txSource_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _txSource_xscrollcommand(self, *args):
        pass

    # _txSource_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _txSource_yscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomMpgui(root)
    root.title('mpgui')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
