""" mpgui_ui.py --

 UI generated by GUI Builder Build 146 on 2012-01-08 22:22:31 from:
    /home/nimmer/code/mp-layer/gui-layout/mpgui.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Mpgui(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._frame_2 = Tkinter.Frame(root,
        )
        self._frame_3 = Tkinter.Frame(root,
        )
        self._butAdd = Tkinter.Button(self._frame_2,
            text = "Add",
            width = 10,
        )
        self._butExit = Tkinter.Button(self._frame_2,
            text = "Exit",
            width = 10,
        )
        self._panedwindow_1 = Tkinter.PanedWindow(self._frame_2,
            height = 0,
            width = 0,
        )
        self._txtStatus = Tkinter.Text(self._frame_1,
            height = 0,
            width = 0,
        )
        self._scrStatus = Tkinter.Scrollbar(self._frame_1,
        )
        self._lstFiles = Tkinter.Listbox(self._frame_3,
            height = 7,
            width = 0,
        )
        self._scrFiles = Tkinter.Scrollbar(self._frame_3,
        )

        # widget commands

        self._butAdd.configure(
            command = self._butAdd_command
        )
        self._butExit.configure(
            command = self._butExit_command
        )
        self._txtStatus.configure(
            xscrollcommand = self._txtStatus_xscrollcommand
        )
        self._txtStatus.configure(
            yscrollcommand = self._txtStatus_yscrollcommand
        )
        self._scrStatus.configure(
            command = self._scrStatus_command
        )
        self._lstFiles.configure(
            xscrollcommand = self._lstFiles_xscrollcommand
        )
        self._lstFiles.configure(
            yscrollcommand = self._lstFiles_yscrollcommand
        )
        self._scrFiles.configure(
            command = self._scrFiles_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_2.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_3.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._butAdd.grid(
            in_    = self._frame_2,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._butExit.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 10,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._panedwindow_1.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._txtStatus.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._scrStatus.grid(
            in_    = self._frame_1,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )
        self._lstFiles.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._scrFiles.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ns"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 78, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 180, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 39, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 452, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_rowconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


