#!/usr/bin/env python
""" mpgui.py --

 UI generated by GUI Builder Build 146 on 2012-01-08 22:22:32 from:
    /home/nimmer/code/mp-layer/gui-layout/mpgui.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from mpgui_ui import Mpgui

# BEGIN USER CODE global

# END USER CODE global

class CustomMpgui(Mpgui):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _butAdd_command --
    #
    # Callback to handle _butAdd widget option -command
    def _butAdd_command(self, *args):
        pass

    # _butExit_command --
    #
    # Callback to handle _butExit widget option -command
    def _butExit_command(self, *args):
        pass

    # _lstFiles_xscrollcommand --
    #
    # Callback to handle _lstFiles widget option -xscrollcommand
    def _lstFiles_xscrollcommand(self, *args):
        pass

    # _lstFiles_yscrollcommand --
    #
    # Callback to handle _lstFiles widget option -yscrollcommand
    def _lstFiles_yscrollcommand(self, *args):
        pass

    # _scrFiles_command --
    #
    # Callback to handle _scrFiles widget option -command
    def _scrFiles_command(self, *args):
        pass

    # _scrStatus_command --
    #
    # Callback to handle _scrStatus widget option -command
    def _scrStatus_command(self, *args):
        pass

    # _txtStatus_xscrollcommand --
    #
    # Callback to handle _txtStatus widget option -xscrollcommand
    def _txtStatus_xscrollcommand(self, *args):
        pass

    # _txtStatus_yscrollcommand --
    #
    # Callback to handle _txtStatus widget option -yscrollcommand
    def _txtStatus_yscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomMpgui(root)
    root.title('mpgui')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
